sequenceDiagram
    participant browser
    participant server 
    browser->> server: HTTP GET https://studies.cs.helsinki.fi/exampleapp/spa
    server ->> browser: HTML document 
    browser ->> server: HTTP GET https://studies.cs.helsinki.fi/exampleapp/main.css 
    server ->> browser: main.css 
    browser ->> server: HTTP GET httstudies.cs.helsinki.fi//exampleapp/spa.js 
    server ->> browser: spa.js 
    Note left of browser: browser starts executing javascript to get data.json from server 
    browser ->> server: HTTP GET studies.cs.helsinki.fi//exampleapp/data.json
    server ->> browser: {{...}}

