# fly.toml app configuration file generated for phonebookfullstackopen2023 on 2023-11-21T14:57:59+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "phonebookfullstackopen2023"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
